name: calling-workflow

on:
  workflow_call:

jobs:
  copy-pre-commit:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: 'asenindbt/reusable-workflow-poc'
          path: 'reusable-workflow-poc'
          ref: 'main' # This can be a tagged version as well

      - name: Upload org-wide pre hook as an artefact
        uses: actions/upload-artifact@v4
        with:
          name: org-wide-pre-commit-hook
          path: reusable-workflow-poc/orghooks.yaml
          retention-days: 1

      - name: Checkout sample repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      # Download the org-wide pre-hook artefact
      - name: Download org-wide pre-hook artefact
        uses: actions/download-artifact@v4
        with:
          name: org-wide-pre-commit-hook

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run org-wide pre-commit hook
        run: |
          pre-commit run --config "./orghooks.yaml" --all-files
