# This is a basic workflow to help you get started with Actions

name: calling-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Print repo name
        run: |
          echo ${{ inputs.repo-name }}

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          path: 'reusable-workflow-poc'
          ref: 'main'

      - name: Check file directory - no. 1
        run: |
          ls -la

      # TODO not sure if this is needed
      - name: Checkout sample repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo-name }}
          ref: 'main'
          # path: 'reusable-workflow-poc'

      - name: Copy org wide pre-commit config file to target repo
        run: |
          cp reusable-workflow-poc/orghooks.yaml .

      - name: Check file directory - no. 2
        run: |
          ls -la

#      - name: Check root directory
#        run: |
#          ls -la
#
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.10"
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pre-commit
#
#      - name: Run org-wide pre-commit hook
#        run: |
#          pre-commit run --config "./orghooks.yaml" --files
