name: CI

on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: 'asenindbt/reusable-workflow-poc'
          path: 'reusable-workflow-poc'
          ref: 'main'

      # Copies org hooks to another file
      - name: Check for orghooks
        run: |
          cat reusable-workflow-poc/.github/workflows/orghooks.yaml

      - name: Test output
        run: |
          echo "hello there" >> $GITHUB_OUTPUT
